### ISSUE TITLE
Add final restart file at terminal heating points/ md runs

### ISSUE THREAD

**Issue by harveydevereux** [stfc/janus-core#115]
As discussed in #108 the addition is to dump additional ```xyz``` files at the end of heating steps, and md runs

**Comment by harveydevereux** [comment]
There is a [wip](https://github.com/stfc/janus-core/compare/main...harveydevereux:janus-core:final_restart)

**Comment by alinelena** [comment]
hi @harveydevereux can you please open a pr, and @ElliottKasoar will give the first review

**Comment by harveydevereux** [comment]
> hi @harveydevereux can you please open a pr, and @ElliottKasoar will give the first review

will do once I have sorted the tests I broke as we just talked about

**Comment by ElliottKasoar** [comment]
> > hi @harveydevereux can you please open a pr, and @ElliottKasoar will give the first review
> 
> will do once I have sorted the tests I broke as we just talked about

@harveydevereux you can always open it as a draft. I know you've linked it in this case so it doesn't make a huge difference, but generally the earlier we can start to take a look the better.
