### ISSUE TITLE
Version check fails for publish workflow

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/janus-core#125]
Currently, the version check when publishing to PyPI fails, as the workflow runs `poetry build`, which builds the source and wheels archives, but does not actually install janus-core, leading to the error:

```
importlib.metadata.PackageNotFoundError: No package metadata was found for janus-core
```

One option would be to run `poetry install` within the publish workflow, which should solve the issue, but adds considerable extra work. Alternatively, we could remove the `__init__` version check, as it's no longer manually specified.

I'd lean towards the latter, but I think either should work.

Preferences, @alinelena, @oerc0122?

**Comment by alinelena** [comment]
personally I will remove the check since now we really have only one version
