### ISSUE TITLE
Split up helpers directory?

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/janus-core#144]
@federicazanca noted that [train.py](https://github.com/stfc/janus-core/blob/main/janus_core/helpers/train.py) in [helpers](https://github.com/stfc/janus-core/tree/main/janus_core/helpers) doesn't exactly fit with other files in the directory, e.g. [utils.py](https://github.com/stfc/janus-core/blob/main/janus_core/helpers/utils.py) or [janus_types.py](https://github.com/stfc/janus-core/blob/main/janus_core/helpers/janus_types.py), which are used more as developer tools.

I originally placed train.py here because it seems closest to [mlip_calculators.py](https://github.com/stfc/janus-core/blob/main/janus_core/helpers/mlip_calculators.py), as opposed to single point calculations etc. in the [calculations](https://github.com/stfc/janus-core/tree/main/janus_core/calculations) directory, but perhaps a third alternative for user-facing modules such as train.py and (to a lesser extent) mlip_calculators.py would be more appropriate?

**Comment by alinelena** [comment]
yes good idea
