### ISSUE TITLE
Inconsistent EoS README/file naming

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/janus-core#157]
In tidying up the EoS PR, the output file name in the EoS section of the README was changed:

> ```
> janus eos --struct tests/data/NaCl.cif --no-minimize --min-volume 0.9 --max-volume 1.1 --n-volumes 9 --arch mace_mp --calc-kwargs "{'model' : 'small'}"
> ```
>
> This will save the energies and volumes for nine lattice constants in NaCl-eos.dat, and the fitted minimum energy, volume, and bulk modulus in **NaCl-eos.dat**, in addition to generating a log file, eos.log, and summary of inputs, eos_summary.yml.

However, when I run the command, I still get ` NaCl-eos-fit.dat` and `NaCl-eos-raw.dat`, which are the files originally mentioned.

Was the intention to rename the files that are created?

**Comment by alinelena** [comment]
yes,  keep -fit and -raw
