### ISSUE TITLE
Inconsistent Phonon README/file naming

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/janus-core#158]
The current README lists this command and set of output files
>
>```
>janus phonons --struct tests/data/NaCl.cif --supercell 2x2x2 --minimize --arch mace_mp --calc-kwargs "{'model' : 'small'}"
>```
>This will save the Phonopy parameters, including displacements and force constants, to NaCl-params.yml, and the calculated band structure to NaCl-auto-band.yml, in addition to generating a log file, phonons.log, and summary of inputs, phonons_summary.yml.

However, when I run this command  get `NaCl-phonopy.yml` and `NaCl-force_constants.hdf5` instead of `NaCl-params.yml` and ` NaCl-auto-band.yml`.

Similarly for the second example:

>
>```
>janus phonons --struct tests/data/NaCl.cif --supercell 2x3x4 --dos --pdos --thermal --temp-start 0 --temp-end 300 --temp-step 50
>```
>This will create additional output files: NaCl-cv.dat for the thermal properties (heat capacity, entropy, and free energy) between 0K and 300K, NaCl-dos.dat for the DOS, and NaCl-pdos.dat for the PDOS.

I get `NaCl-thermal.dat` instead of `NaCl-cv.dat`

**Comment by alinelena** [comment]
shall be thermal since that file constains more than CV

**Comment by alinelena** [comment]
also without --band shall not generate a dos.
there is another pr open to add extra info we can fix it in there.
