### ISSUE TITLE
Add CI testing for extra MLIPs

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/janus-core#161]
Now that we have a few more tests for non-MACE MLIPs (calculator tests, and now EoS tests), we should add their tests into the Actions CI.

This requires adding the `--run-extra-mlips` flag for pytest, but will also require changing the installation to include the extra-mlips poetry group.

I'm still getting inconsistent errors for the EoS tests, so this would be a useful second check for that too.

**Comment by ElliottKasoar** [comment]
Alternatively (also suggested by @alinelena) we can promote the two MLIPs to non-optional dependencies.

Also note that the bug appears to due MACE setting the torch data type, which explains the inconsistency. A solution may involve using: https://pytorch.org/docs/stable/generated/torch.set_default_dtype.html

**Comment by ElliottKasoar** [comment]
Do they accept alternative precisions at all?

If they do, ideally we'd set it to that, but I can't see anywhere where a precision would be used.

If not, just setting it is probably safest.

**Comment by alinelena** [comment]
I do not think so, or I am blind and missed it

**Comment by ElliottKasoar** [comment]
> Alternatively (also suggested by @alinelena) we can promote the two MLIPs to non-optional dependencies.

This is currently the plan, although it seems like there are a few relatively new installation bugs related to dgl (see [failed action](https://github.com/ElliottKasoar/janus-core/actions/runs/9370066059/job/25796074588) and [potentially related issue](https://github.com/dmlc/dgl/issues/7433)) and chgnet (see [issue](https://github.com/CederGroupHub/chgnet/issues/160)), which may need resolving first.

We can probably use older versions with an upper limit as a temporary solution if these issues aren't resolved quickly.

**Comment by alinelena** [comment]
yes chgnet seems to be problematic I had to install it from git, matgl(m3gnet) shall be ok but let us do them together... is not to be done before 20. in the docker image we have all of them installed.
