### ISSUE TITLE
Add auto restart for MD

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/janus-core#169]
> 3. autorestart shall be a different option and only for MD not for heating(this is to workaround supercomputers with easy access on preemptable queues.)

_Originally posted by @alinelena in https://github.com/stfc/janus-core/issues/108#issuecomment-2134808423_

**Comment by alinelena** [comment]
at the moment we do for a restart

```
janus md --config npt.yml --struct UiO-66Zr-NH2-T300K.extxyz
```

followed by 
```
OMP_NUM_THREADS=8 janus md --config npt.yml --struct UiO-66Zr-NH2-T300K-npt-T300.0-p0.0-res-11000.extxyz --restart --struct-name UiO-66Zr-NH2-T300K
```

we would like something like 

```
janus md --config npt.yml --struct UiO-66Zr-NH2-T300K.extxyz --restart
```

to achieve the two above 

shall find the last restart file -res-*.extxyz use it to restart and continue to append to both traj and stats files

**Comment by alinelena** [comment]
another point to keep in mind, at the moment restart adds steps from input file to the current step rather than the limit becoming last_step + n_steps
