### ISSUE TITLE
Update ASE

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/janus-core#178]
A new release of ASE has now been published, which breaks a few tests:

- [x] tests/test_eos_cli.py::test_eos
- [x] tests/test_geom_opt.py::test_hydrostatic_strain
- [x] tests/test_geom_opt.py::test_restart
- [x] tests/test_geomopt_cli.py::test_traj
- [x] tests/test_geomopt_cli.py::test_fully_opt
- [x] tests/test_geomopt_cli.py::test_fully_opt_and_vectors
- [x] tests/test_single_point.py::test_single_point_write
- [x] tests/test_single_point.py::test_single_point_write_kwargs
- [x] tests/test_singlepoint_cli.py::test_singlepoint

These need resolving before ASE can be unpinned (see: #177).

**Comment by alinelena** [comment]
i will suggest to update the ase version and the tests in the same pr.
