### ISSUE TITLE
NaNs in SinglePoint CLI output file

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/janus-core#182]
If I run `janus singlepoint --struct tests/data/benzene.xyz --arch mace_mp` the output file contains

```
stress="-inf -inf nan -inf -inf nan nan nan nan"
```

suggesting the data is not entirely being cleaned up.

On the Python side, it doesn't seem to be stored in the `struct.info` or `results` dictionaries, but NaNs are still present in `struct.calc.results`, so I suspect that is the source.

**Comment by alinelena** [comment]
odd I thought I cleaned  it
