### ISSUE TITLE
dft code for aiida incompatible with janus

### ISSUE THREAD

**Issue by federicazanca** [stfc/janus-core#196]
If we need to do a training workflow using aiida-quantumespresso (dft optimisation with qe --> training with janus), we need to add aiida-quantumespresso to the dependencies of aiida-mlip (or at least have it installed at the same time as janus cause we need to use both). 
The problem is that janus and aiida-qe have some dependencies conflict:

```
And because janus-core (0.6.1b0) depends on seekpath (>=2.1.0,<3.0.0)
 and janus-core (0.6.2) depends on seekpath (>=2.1.0,<3.0.0), janus-core (>=v0.6.0b0,<0.7.0) requires seekpath (>=2.1.0,<3.0.0). 
And because aiida-quantumespresso (>=4.6.0,<5.0.0) requires seekpath (>=1.9.3,<2.0) (1), aiida-quantumespresso (>=4.6.0,<5.0.0) is incompatible with janus-core (>=v0.6.0b0,<0.7.0)
``` 

Can we change the version of seekpath in janus-core?
Should I use another dft code?
Other solutions?

**Comment by ElliottKasoar** [comment]
For context, `seekpath` is an [optional dependency](https://github.com/phonopy/phonopy?tab=readme-ov-file#dependency) for phonopy which allows plotting the phonon band structure.

I haven't seen anywhere where they explicitly state which versions are compatible, so it may be possible to change our requirements to resolve the conflict.

Given that `seekpath` 2.0 has been out for more than four years, I'd rather avoid downgrading if possible though.
