### ISSUE TITLE
Add user/dev guide

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/janus-core#23]
As discussed in #22 

To do:

- [x] Use guide:
  - [x] Getting started (covered by README for now)
  - [x] Tutorial (covered by [janus-tutorials](https://github.com/stfc/janus-tutorials/) for now)
- [x] Developer guide:
  - [x] Getting started
  - [x] Tutorial
- [ ] Contribution guide

**Comment by alinelena** [comment]
part of this we need to add contribution guide.
