### ISSUE TITLE
Installation error for torch-scatter

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/janus-core#235]
When trying to install sevennet, I encounter errors similar to: https://github.com/rusty1s/pytorch_scatter/issues/413

Fortunately, the latest sevennet release, which we already use (0.9.3), appears to have [dropped it as a dependency](https://github.com/MDIL-SNU/SevenNet/pull/53/commits/a5d4c6b6be1a0433208048b4178b3bf3d9491d92), so I propose we do the same.

**Comment by alinelena** [comment]
odd. go ahead
