### ISSUE TITLE
post-process issues

### ISSUE THREAD

**Issue by oerc0122** [stfc/janus-core#253]
- [x] Mismatched argument names - filename, filenames
- [ ] Data not returned on vafs
- [x] `str` is `Sequence` so passing string as filename does not work.

**Comment by ElliottKasoar** [comment]
Are all of these resolved by #274? I'm not sure the vaf data is returned?

**Comment by oerc0122** [comment]
Ah, I wrote fixes, not addresses. What VAF data are we wanting?

**Comment by alinelena** [comment]
just the data to be able to print the graph correlation vs lag the same way we dump the rdf.dat
