### ISSUE TITLE
Tab completion slow and raises warnings

### ISSUE THREAD

**Issue by ajjackson** [stfc/janus-core#267]
Apologies if this was already spotted/fixed, I am using 0.6.2.

The typer command-line interface allows shell completions to be installed for a nicer interactive experience. However, when I try to use these, or run the `--help` command:

a) the response is quite slow, which negates the workflow improvement
b) sometimes minor deprecations warnings are raised by dependencies such as e3nn/pytorch.

This could probably be avoided by delaying the import of these modules so that it is possible for typer to do whatever it wants to do without loading a lot of dependencies.

**Comment by alinelena** [comment]
spotted yes, fixed not yet.
