### ISSUE TITLE
add system name label

### ISSUE THREAD

**Issue by alinelena** [stfc/janus-core#293]
at the moment when we write we do not add a system name label

that will be useful especially if one wants to filter structures.
something like system_name and infer from the file name will be useful.

**Comment by ElliottKasoar** [comment]
Is this effectively bringing back `struct_name`, since we had the option to manually set that, but otherwise it would default to the file path (or formula as a last resort), or do you mean something else?

Also by label do you mean via `Atoms.info`?

**Comment by alinelena** [comment]
nope what I mean... infer it from file name and save it in info['system_name']

**Comment by ElliottKasoar** [comment]
My point is the inference is part of what `struct_name` did before, and if we're going to add labels for users, particularly ones they might use to search, you might expect it to be user-definable as well?

I know it was beyond what you were suggesting, but it seemed like where we might end up.

If we only ever want to save the filename stem though, that's fine.

**Comment by alinelena** [comment]
in general the data labeling shall be a sperated issue and once people get more used we do not need it... adding a system_name is minimal
