### ISSUE TITLE
Out of date Atoms info for MD

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/janus-core#302]
Some keys `self.dyn.atoms.info`, such as `"real_time"` and `"density"`, are not necessarily updated before Atoms objects are written out. 

For example, these are set in [get_stats](https://github.com/stfc/janus-core/blob/main/janus_core/calculations/md.py#L174), but not updated when writing out the trajectory, restart files, etc., meaning these values only change at the frequency the statistics are updated.

We could either remove these keys before writing out other files, or update them before writing.

For the latter, it would be relatively straightforward for `"density`", but possibly slightly more complicated for `"real_time"` due to the way we update it.

However, currently `"real_time"` isn't actually printed in the info due to its format, so we could leave that and only update `"density`". e.g. by updating [_set_time_step](https://github.com/stfc/janus-core/blob/main/janus_core/calculations/md.py#L512)

**Comment by alinelena** [comment]
density is needed, especially for npt

**Comment by ElliottKasoar** [comment]
Would you assume it's always in the info though, since it can always be calculated if needed?

(Just wondering, I'm perfectly happy for it to be fixed so it's still written, but up-to-date.)
