### ISSUE TITLE
mesh is missing as an option for phonons

### ISSUE THREAD

**Issue by alinelena** [stfc/janus-core#305]
mesh, that is passes to run mesh shall be a cli option, also is missing for run_thermal

**Comment by ElliottKasoar** [comment]
Ah yep, we're inconsistent in all three places:

```
self.results["phonon"].run_mesh()
self.results["phonon"].run_mesh(mesh)
self.results["phonon"].run_mesh(
    mesh, with_eigenvectors=True, is_mesh_symmetry=False
)
```

Also to check, do you know how repeat runs of the mesh interact?

**Comment by alinelena** [comment]
yap will be useful.
