### ISSUE TITLE
codecarbon errors from multiple instances

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/janus-core#314]
CI seems to be failing, possibly due to changes to codecarbon 2.6 -> 2.7, as the errors relate to `AttributeError("'OfflineEmissionsTracker' object has no attribute '_scheduler'")`

**Comment by alinelena** [comment]
Yap and is not very reproducible

**Comment by JcGuan** [comment]
Hi Elliott, many thanks for looking into the CodeCarbon issue. I'm Jingcheng working with Alin on MLIP MD calculations. I saw this CodeCarbon error on Scarf about 10 days ago while running multiple restarted MD calculations using CPUs. I have a feeling that this is not a problem for non-restart/new MD calculations, but is only seen for restarted ones. As users are allowed to run one GPU job at a time on Scarf, this is probably hard to reproduce with GPU, I think.

**Comment by alinelena** [comment]
in theory having multiple instances is correct and cc shall work, what are the implications of using allow_multiple_runs looks to me that shall be the default anyhow.

**Comment by ElliottKasoar** [comment]
Since I think all it can measure are the power supplied to the hardware, and the total time of processes (https://mlco2.github.io/codecarbon/methodology.html), would we not expect multiple instances to significantly overestimate the energy usage?

Perhaps for now we can set `allow_multiple_runs=True` to revert the behaviour, but I can open an issue with codecarbon to 1) improve the error handling and 2) hopefully clarify any reason not to use allow_multiple_runs

**Comment by alinelena** [comment]
yap I think so. in theory the info is correct since is the energy the machine used, not the process, if I understand correctly that will be the case even with a single process.
