### ISSUE TITLE
add data reduction to hdf5

### ISSUE THREAD

**Issue by alinelena** [stfc/janus-core#37]

**Comment by ElliottKasoar** [comment]
Is this referring to [pre-processing data](https://github.com/ACEsuit/mace/blob/main/mace/cli/preprocess_data.py) (e.g. xyz -> hdf5 input for training)?

If so, should it just be an extra option as part of training, or would you run it on its own first?

**Comment by alinelena** [comment]
yes that is what I refer to. since is general is a one off, would be useful to be on its own
