### ISSUE TITLE
Change coverage requirements

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/janus-core#46]
Currently we have 100% coverage, and the CI is set to fail if this decreases at all.

This isn't necessarily realistic to maintain long term in general, but there also appears to be a more immediate issue, as code such as comments can be detected as [untested](https://coveralls.io/builds/65950825/source?filename=janus_core%2Fsingle_point.py#L14).

Options include setting a maximum decrease in coverage (might fail in the above case, but in most cases is unlikely to once the code base is built up ), a minimum total coverage, or setting allow-on-fail.

**Comment by alinelena** [comment]
i think in unit test coverage we shall aim for 90% or so and then add some more complex tests as we discussed. in general we need to be reasonable

**Comment by ElliottKasoar** [comment]
Yes, I think the thing we need to decide is what we strictly enforce (assuming we want to keep the successful Actions tick), which unfortunately seems to need to take into account mislabelled code, so be more flexible than we're necessarily aiming for.

In our contributor guidelines we can set out more ambitious targets.
