### ISSUE TITLE
Add option to provide Atoms objects for structure

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/janus-core#47]
Currently single point calculations and geometry optimization expect a file path/string, but as suggested by @alinelena, it would also be useful to be able to pass ASE `Atoms` objects directly.

We could overload `read_system` (or similar), which would also allow us to extend this to further similar Atoms-like objects in the future.

**Comment by oerc0122** [comment]
The thing here is the optional(?) dependencies can get quite messy. Then again things like `functools.singledispatch` can make it quite clean.

**Comment by ElliottKasoar** [comment]
ASE isn't optional, so I think for this it should be fine. If/when we want to extend it further, we'll definitely have to think more carefully.
