### ISSUE TITLE
add test for geom opt convergence

### ISSUE THREAD

**Issue by federicazanca** [stfc/janus-core#82]
there needs to be some testing for when the geometry optimisation does not converge in a specified number of steps and raises some error

**Comment by ElliottKasoar** [comment]
I think the current behaviour is that it just stops after the number or steps or reaching the force threshold, without any error.

I assume we'd still want to return the Atoms object in Python and/or save the structure, so we don't necessarily want to throw a proper error. Maybe just raise a warning?

(As noted in #83, there's not currently much control over this in the CLI, but should hopefully be straightforward to add as additional kwargs dictionaries)

**Comment by alinelena** [comment]
practically what we need is to read/caputure the log and check is the fmax is smaller than what is expected... we need to see if we can get this in an elegant way without parsing the log
