### ISSUE TITLE
Add option for intel devices?

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/janus-core#95]
MACE seems to have [added support](https://github.com/ACEsuit/mace/pull/356) for the "xpu" device (at least for training) via the `intel_extension_for_pytorch` package.

I imagine this could be useful for anyone using the new Intel PVCs via [Dawn](https://www.hpc.cam.ac.uk/d-w-n), and elsewhere.

We can certainly add `xpu` as a valid device type straightforwardly. I think everything else can be handled by the individual MLIP calculators, so that may be all that's required?

**Comment by alinelena** [comment]
yap shall be added, also the config file got merged we shall check it.
